In [1]:
import numpy as np

In [2]:
x1 = np.array([4,5,6])
print(x1)
print(x1.shape)

[4 5 6]
(3,)


In [5]:
x = np.array([[4],[5],[6]])
print(x)
print(x.shape)
print(x[0][0])
#treated as 2 dimensional
#reshape operation
x= x.reshape((-1,))
print(x)

[[4]
 [5]
 [6]]
(3, 1)
4
[4 5 6]


In [6]:
#Here X is a matrix
X= np.array([[4,5,6],[3,4,2],[5,7,8]])
print(X.shape)


(3, 3)


In [7]:
#Here T is a tensor
T= np.array([[[4,5,7],[2,5,7]],[[4,7,9],[2,5,8]]])
print(T.shape)

(2, 2, 3)


In [8]:
#Transpose
print(X)
xt = np.transpose(X)
print(xt)

[[4 5 6]
 [3 4 2]
 [5 7 8]]
[[4 3 5]
 [5 4 7]
 [6 2 8]]


In [13]:
#Broadcasting
l = [1,2,3,4]
l=np.array(l)
l=l+1
#it will add 1 to all the elements
print(l)

[2 3 4 5]


In [14]:
#Matrix Multiplication
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(x.shape)
print(y.shape)
print(x)
print(y)


(3, 3)
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [15]:
prod = np.dot(x,y)
print(prod)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [17]:
#element wise multiplication: hadamard product
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.eye(3)
y=(y**2) +1
print(x)
print(x*y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2.  2.  3.]
 [ 4. 10.  6.]
 [ 7.  8. 18.]]


In [18]:
#Norms
x = np.array([-1,2,3])
lp2 = np.linalg.norm(x)
print(lp2)

3.7416573867739413


In [20]:
lp1 = np.linalg.norm(x,ord=1)
print(lp1)

6.0


In [21]:
lpinf = np.linalg.norm(x,ord=np.inf)
print(lpinf)

3.0
